shop/products/urls.py
from django.urls import path

from .views import ProductsView

app_name = 'products'
urlpatterns = [
    path('', ProductsView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsView.as_view(), name='category'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace='products')),
]

shop/counter/models.py
from django.contrib.auth.models import User
from django.db import models


class VisitsCounter(models.Model):
    """The model for counting page visits by registered users"""
    path = models.CharField(max_length=500)
    counter = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.user} | {self.path} | {self.counter}'

shop/products/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.db.models import Manager


class AvailableQuerySet(models.QuerySet):
    """Customizing queryset to get undeleted objects"""
    def not_deleted(self):
        return self.filter(is_deleted=False)


class AvailableManager(Manager):
    """Customizing model Manager to get undeleted objects"""
    def get_queryset(self):
        return AvailableQuerySet(self.model, using=self._db)

    def not_deleted(self):
        return self.get_queryset().not_deleted()


class Section(models.Model):
    """The model of categories of goods"""
    name = models.CharField(max_length=64)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, default='1')
    is_deleted = models.BooleanField(default=False, null=False)

    # objects = AvailableManager()
    objects = Manager()
    on_site = CurrentSiteManager()

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    """The model of the received goods"""

    name = models.CharField(max_length=100)
    received_on = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    measure = models.CharField(max_length=15)
    supplier_name = models.CharField(max_length=160)
    category = models.ManyToManyField(Section, blank=True)
    site = models.ManyToManyField(Site)

    objects = Manager()
    on_site = CurrentSiteManager()

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'{self.name} "{self.supplier_name}"'

shop/counter/views.py
from django.shortcuts import render

# Create your views here.

shop/products/views.py
from django.views.generic import ListView

from products.models import Product, Section


class ProductsView(ListView):
    model = Product
    template_name = 'products/goods_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['title'] = 'Добро пожаловать'
        context['site_name'] = self.request.site.name
        context['categories'] = Section.on_site.all()
        if self.kwargs.keys():
            context['section'] = Section.on_site.get(id=self.kwargs['category_id'])
        return context

    def get_queryset(self):
        if self.kwargs.keys():
            return Product.on_site.filter(category=self.kwargs['category_id'])
        return Product.on_site.all().prefetch_related('category')


class CategoryView(ListView):
    model = Product
    template_name = 'products/goods_list.html'

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{ title }}</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>

</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand oranged" href="{% url 'products:index' %}">Главная</a>
    <button class="btn btn-link btn-md m-2 order-1 order-lg-0 btn-orange blacked" id="sidebarToggle"><i
            class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->

    <form class="d-none d-md-inline-block form-inline ml-auto mr-0
    mr-md-3 my-2 my-md-0" action="#" method="get">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..."
                   name="search_panel" aria-label="Search" aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit"><i class="fas fa-search oranged"></i></button>
            </div>
        </div>
    </form>

    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle rounded btn-orange blacked" id="userDropdown" role="button"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw blacked"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">

                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="/admin/logout/?next=/">Выйти из профиля</a>
                {% else %}
{#                    <a class="dropdown-item" href="">Регистрация</a>#}
                    <a class="dropdown-item" href="/admin/login/?next=/">Авторизация</a>
                {% endif %}

            </div>
        </li>
    </ul>
</nav>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Разделы</div>
                {% for category in categories %}
                    <a class="nav-link" href="{% url 'products:category' category.id %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-boxes oranged"></i>
                        </div>
                        {{ category }}
                    </a>
                {% endfor %}

                    {% if user.is_authenticated %}
                        <a class="nav-link" href="#">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-user oranged"></i>
                            </div>
                            Мой профиль
                        </a>
                        <a id="my_profile"></a>
                    {% else %}
                        <a class="nav-link" href="/admin/login/?next=/">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-user oranged"></i>
                            </div>
                            Авторизация на сайте
                        </a>
                    {% endif %}
                    {% if user.is_staff %}
                        <input type="button" class="btn btn-block btn-orange blacked"
                               onclick="window.location.href = '/admin';"
                               value="К админке"/>
                    {% endif %}
                    <button onClick="javascript:history.go(-1);" type="submit" class="btn btn-block btn-orange blacked">
                        <i class="fa fa-undo"></i> Назад
                    </button>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://kit.fontawesome.com/2b537a4c3e.js" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/products/goods_list.html
{% extends 'base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center mt-5">
            <p>Info: {{ site_name }}</p>
                <h1>
                    {% if section %}
                        Товары раздела <b class="oranged">{{ section.name }}</b>
                    {% else %}
                        <b class="oranged">Все товары</b>
                    {% endif %}
                </h1>
                <table class="font-xl m-2">
                    <thead>
                    <tr id="table-headers">
                        <th>Наименование</th>
                        <th>Поставщик</th>
                        <th>Цена, руб.</th>
                        <th>Ед. изм.</th>
                        <th>Дата добавления</th>
                        <th>Сайт</th>
                        {% if not section %}<th>Разделы</th>{% endif %}
                    </tr>
                    </thead>
                    {% for product in object_list %}
                        <tr id="table-rows">
                            <td>{{ product.name }}</td>
                            <td>{{ product.supplier_name }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.measure }}</td>
                            <td>{{ product.received_on | date }}</td>

                             <td>
                                    <ul>{% for item in product.site.all %}
                                        <li class="text-left">{{ item.name }}</li>
                                    {% endfor %}</ul>
                                </td>

                            {% if not section %}
                                <td>
                                    <ul>{% for item in product.category.all %}
                                        <li class="text-left">{{ item }}</li>
                                    {% endfor %}</ul>
                                </td>
                            {% endif %}


                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col text-center">
                <a class='btn btn-outline-dark btn-orange ml-3 mb-1'
                   href='/admin/products/product/add/'>Добавить товар</a>
            </div>
        </main>
    </div>

{% endblock %}